version: '2'
services:
  influxdb:
    restart: always
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
      - INFLUXDB_HTTP_LOG_ENABLED=false
    logging:
      driver: none
  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    logging:
      driver: none
  airquality:
    image: airquality
    restart: always
    privileged: true
    environment:
      - INFLUXDB_HOST=influxdb
      - PYTHONUNBUFFERED=1
    volumes:
      - ./.env:/app/.env
    depends_on:
      - influxdb
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 10m
volumes:
  influxdb-storage:
  grafana-storage: