services:
  airquality:
    image: ghcr.io/marcoglauser/airquality:master
    restart: always
    privileged: true
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - ./.env
    networks:
      - homeassistant_homeassistant
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 10m

networks:
  homeassistant_homeassistant:
    external: true